yarn.lock

Fix: yarn lock

---

components/ReservationController.jsx
components/states/InitialState.jsx
components/states/StateController.jsx
utils/state-machine.js

Add xtate to React.
Guide: https://xstate.js.org/docs/recipes/react.html#global-state-react-context

Feat: add react xstate machine

---

components/states/ReservationTypeState.jsx
components/states/StateController.jsx
utils/state-machine.js

Set reservation type on the context when transitioning states

Feat: set state on reservation type state

---

pages/home.js
pages/index.js
pages/reservation.js

Rename `reservation` and set it to `index`
Change `index` -> `home`

change index and reservation pages

---

package-lock.json
package.json
pages/api/hello.js
pages/api/mail.js
yarn.lock

adding sendgrid mail service

---

components/states/CertificationDiveState.jsx
components/states/CompleteState.jsx
components/states/ReservationTypeState.jsx
components/states/StateController.jsx
utils/state-machine.js

Changes in PR:
1. Add new last state, that displays data submitted by suer
2. Add new features to update the sate
3. Add actions to all the cards in the current state

rename last state

---

package.json
yarn.lock

Improve a copule of libraries to make sure we don't stay behind

Feat: upgrade libraries

---

components/states/CalendarState.jsx
components/states/CompleteState.jsx
components/states/shared/StatePage.jsx
components/states/shared/StateTitle.jsx
pages/index.js
utils/state-machine.js

- Feat: add UI improvements to the state flow
- Feat: add hour pills to calendar state
UI for hour pills:

improvements to state

---

components/states/DeepestDiveState.jsx
components/states/LastDiveState.jsx
components/states/StateController.jsx
utils/state-machine.js

Transition from deepest dive to last dive

addidn transition from deepest dive to last dive

---

components/states/DiverInformationState.jsx
components/states/StateController.jsx
package.json
pages/_app.js
utils/state-machine.js
yarn.lock

Making it simple for now, and we can add to it later (was not fan of the other 2 libraries)

Feat: Add diver information state

---

components/BackButton/index.jsx
components/states/CalendarState.jsx
components/states/DiverInformationState.jsx
components/states/LastDiveState.jsx
package-lock.json
package.json
utils/state-machine.js
yarn.lock

finalized forward state transitions

finalized forward state transitions

---

components/signup/DiveShopConfig.jsx
components/signup/DiveShopInfo.jsx
components/signup/Machine.jsx
components/signup/StateController.jsx
package.json
pages/signup.js
utils/dive-shop-state-machine.js
yarn.lock

Signup form that lives at `/signup`.
Note: Missing CSS and mobile UI
UI:

shop signup form

---

.env
components/signup/DiveShopComplete.jsx
components/signup/DiveShopConfig.jsx
components/signup/DiveShopInfo.jsx
package.json
utils/dive-shop-state-machine.js
utils/supabase.js
yarn.lock

Signup form is complete now (still missing adding the data to supabase)

Feat: signup complete

---

components/shared/SharedPage.jsx
components/signup/DiveShopComplete.jsx
components/signup/DiveShopConfig.jsx
components/signup/DiveShopInfo.jsx
components/signup/SignupPage.jsx
components/states/shared/StatePage.jsx
pages/index.js
pages/signup.js

- Feat: fix css
- feat: improvements to page

signup ui page

---

.env.development
components/signup/DiveShopComplete.jsx
components/states/CreateSupabaseState.jsx
components/states/DiveShopConfigFetchState.jsx
components/states/DiverInformationState.jsx
components/states/StateController.jsx
pages/reservation/[url_hash].js
utils/state-machine.js

Fetch dive shop config on reservation

Feat: add fetch of dive shop config

---

components/shared/FormTextField.jsx
components/signup/DiveShopInfo.jsx
components/states/CalendarState.jsx
components/states/CertifiedDiverState.jsx
components/states/DeepestDiveState.jsx
components/states/DiveShopConfigFetchState.jsx
components/states/DiverInformationState.jsx
components/states/EquipmentState.jsx
components/states/LastDiveState.jsx
components/states/shared/CardComponent.jsx
components/states/shared/EquipmentCard.jsx
components/states/shared/SelectComponent.jsx
components/states/shared/StatePage.jsx

FEat: improvements UI

---

components/LanguageSelector.jsx
components/ReservationController.jsx
components/states/CalendarState.jsx
components/states/CertificationDiveState.jsx
components/states/CertifiedDiverState.jsx
components/states/CompleteState.jsx
components/states/CreateSupabaseState.jsx
components/states/DeepestDiveState.jsx
components/states/DiveShopConfigFetchState.jsx
components/states/DiverInformationState.jsx
components/states/EquipmentState.jsx
components/states/LastDiveState.jsx
components/states/NumberOfDivesState.jsx
components/states/ReservationTypeState.jsx
components/states/StateController.jsx
components/states/shared/BackButton.jsx
components/states/shared/EquipmentCard.jsx
components/states/shared/StatePage.jsx
utils/app-text.js

- translating text
- corrctions
- nit

text translation 2

---

components/states/CalendarState.jsx
components/states/DiverInformationState.jsx

removing calendar hours and form validation for diver information

---

components/admin_real/Dashboard.jsx
components/admin_real/ReservationTable.jsx
jsconfig.app.json
pages/admin.js
pages/admin_demo.js
tailwind.config.js

Feat: admin panel initial

---

components/admin_real/Calendar.jsx
utils/supabase.js

Feat: add calendar nits

---

components/admin_real/Calendar.jsx
components/admin_real/ReservationTable.jsx
components/admin_real/utils.js

Pagination for reservation tables with fetch capability

Feat: reservations pagination

---

components/admin_real/mobil/Calendar.jsx
components/admin_real/mobil/calendar.module.css

- Calendar Fetch
- Day cards when user selects date
UI:

Feat: add calendar fetch + day cards on day selection

---

components/admin_real/ReservationBadge.jsx
components/admin_real/desktop/Calendar.jsx
components/admin_real/shared/calendarUtil.js

adding data to modal

---

components/admin_real/ReservationBadge.jsx

modal style

---

components/admin_real/mobil/Calendar.jsx

Fix: calendar mobil

---

components/admin_real/desktop/EditReservationButton.jsx
components/admin_real/shared/reservationTableUtils.js

Adding ability to modify diver information JSON field - fixing some bugs, adding alert for empty fields in reservation edit modal.

additional functionality for crud +bug fixes

---

components/admin_real/shared/Dashboard.jsx
utils/useSize.js

Fix issue of app not loading locally

Fix: reservations not loading bc loading mobile

---

pages/_app.js
pages/signin.js
utils/helpers.js

Fix the redirect that happens after singin in.

Fix: signin redirect

---

components/admin_real/desktop/CreateReservationButton.jsx
components/admin_real/desktop/EditReservationButton.jsx
components/admin_real/desktop/FormField.jsx
components/admin_real/desktop/ReservationFieldsModal.jsx
components/admin_real/desktop/ReservationTable.jsx
components/admin_real/mobil/Calendar.jsx
components/admin_real/shared/constants.js
components/admin_real/shared/reservationTableUtils.js

adding create-reservation functionality, refactoring

---

components/admin_real/desktop/DesktopDashboard.jsx
components/admin_real/shared/Header.jsx
pages/signin.js
utils/helpers.js

Feat: add logout + css

---

components/admin_real/desktop/Body.jsx
components/admin_real/desktop/DeleteReservationButton.jsx
components/admin_real/desktop/ReservationFieldsModal.jsx
components/admin_real/desktop/ReservationTable.jsx
components/admin_real/mobil/ReservationTable.jsx
components/admin_real/shared/reservationTableUtils.js
components/states/ReservationTableContextProvider.jsx

Creating a context provider so that we can re-fetch reservations when a CRUD change is made.

refreshing table when any CRUD operation takes place

---

components/admin_real/mobil/Calendar.jsx

css nits for mobile calendar

---

components/admin_real/mobil/ReservationTable.jsx

Feat: reservation card details

---

components/admin_real/desktop/Calendar.jsx
components/admin_real/desktop/ReservationViewModal.jsx
package.json
yarn.lock

Add modal to view/edit when the user clicks on the calendar view on desktop
UI:

calendar modal

---

pages/signin.js
utils/helpers.js

Feat: add redirect to url

---

components/admin_real/desktop/ReservationViewModal.jsx

Fix: incorrect import

---

components/admin_real/desktop/ReservationFieldsModal.jsx
components/admin_real/mobil/EditSelectedRow.jsx
components/admin_real/mobil/SelectedRow.jsx

edit reservation for mobile

---

components/admin_real/mobil/Calendar.jsx

floating-button

---

components/admin_real/desktop/CreateReservationButton.jsx
components/admin_real/desktop/Dashboard.jsx
components/admin_real/desktop/DeleteReservationButton.jsx
components/admin_real/desktop/EditReservationButton.jsx
components/admin_real/desktop/Sidebar.jsx
components/admin_real/mobil/Calendar.jsx
components/admin_real/mobil/SelectedRow.jsx
components/admin_real/shared/Dashboard.jsx
components/admin_real/shared/reservationTableUtils.js
tailwind.config.js

Main fix:
1. Add `important: true` to tailwindcss so the CSS we add from tailwindcss is not overwritten
Other fixes:
1. minor changes on some components to update css

Fix: flickering

---

components/admin_real/desktop/ReservationFieldsModal.jsx
components/admin_real/desktop/ReservationTable.jsx
components/shared/ReservationTableContextProvider.jsx
utils/api/reservation.js

Add a couple of improvements to the update/create modal in desktop view

Feat: improvements to form

---

components/admin_real/mobil/Calendar.jsx
components/admin_real/mobil/CreateReservationButton.jsx
components/admin_real/mobil/ReservationForm.jsx
components/admin_real/mobil/ReservationTable.jsx
components/admin_real/mobil/SelectedRow.jsx
utils/api/reservation.js

create reservation mobile

---

components/admin_real/desktop/Body.jsx
components/admin_real/desktop/Calendar.jsx
components/admin_real/desktop/DeleteReservationButton.jsx
components/admin_real/desktop/ReservationFieldsModal.jsx
components/admin_real/desktop/ReservationTable.jsx
components/admin_real/mobil/Calendar.jsx
components/admin_real/mobil/ReservationTable.jsx
components/shared/ReservationsContextProvider.jsx
pages/admin.js
utils/api/reservation.js

Using shared context provider for Calendar and Table reservations

update state with crud

---

components/admin_real/mobil/SelectedRow.jsx
utils/supabase.js

using text values

---

components/admin_real/shared/EquipmentPill.jsx
components/admin_real/shared/EquipmentPills.jsx
components/admin_real/shared/reservationTableUtils.js

Only added to the desktop, need to figure out how to add this to:
1. Mobile
2. Edit modal on Desktop
3. Edit modal on Mobil
UI:

Feat: add equipment pills to reservation table desktop

---

components/admin_real/desktop/Body.jsx
components/admin_real/desktop/Customerstable.jsx
components/admin_real/desktop/Dashboard.jsx
components/admin_real/desktop/Sidebar.jsx
components/admin_real/shared/customersTableUtils.js

adding a customers tab

---

components/admin_real/desktop/Body.jsx
components/admin_real/desktop/Dashboard.jsx
components/admin_real/desktop/Sidebar.jsx

adding analytics tab

---

components/admin_real/desktop/Body.jsx
components/admin_real/desktop/Charts.jsx
package-lock.json
package.json
yarn.lock

adding recharts
